package day37_exceptions;

public class TryCatchBlocks2 {
    public static void main(String[] args) {
        System.out.println("Program1 started");

        int[] arr = {1, 2, 3, 4};

    }

}
